# Generated by Django 5.1.3 on 2024-11-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedstock', '0002_alter_product_product_code_alter_warehouse_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.IntegerField(),
        ),
    ]
